openapi: 3.1.0
info:
  contact:
    email: apiteam@swagger.io
  description: "A sample API for managing pets, orders, and users."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger PetStore Demo
  version: 1.0.0
servers:
- url: https://petstore.swagger.io/v2
tags:
- description: Everything about your Pets
  name: pet
- description: Access to PetStore orders
  name: store
- description: Operations about user
  name: user
paths:
  /pet/{petId}/uploadImage:
    post:
      description: ""
      operationId: uploadFile
      parameters:
      - description: ID of pet to update
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/uploadFile_request"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
          description: successful operation
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: uploads an image
      tags:
      - pet
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /pet:
    post:
      description: Add a new pet to the store.
      operationId: addPet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
          application/xml:
            schema:
              $ref: "#/components/schemas/Pet"
        description: Pet object that needs to be added to the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
            application/xml:
              schema:
                $ref: "#/components/schemas/Pet"
          description: Successful operation
        "405":
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
      summary: Add a new pet to the store
      tags:
      - pet
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/xml
    put:
      description: Update an existing pet by Id.
      operationId: updatePet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
          application/xml:
            schema:
              $ref: "#/components/schemas/Pet"
        description: Pet object that needs to be updated
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
            application/xml:
              schema:
                $ref: "#/components/schemas/Pet"
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception
      security:
      - petstore_auth:
        - write:pets
      summary: Update an existing pet
      tags:
      - pet
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/xml
  /pet/findByStatus:
    get:
      description: Multiple status values can be provided with comma-separated strings.
      operationId: findPetsByStatus
      parameters:
      - description: Status values that need to be considered for filter
        explode: false
        in: query
        name: status
        required: true
        schema:
          items:
            enum:
            - available
            - pending
            - sold
            type: string
          type: array
          default: null
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Pet"
                type: array
                default: null
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/Pet"
                type: array
                default: null
          description: Successful operation
        "400":
          description: Invalid status value
      security:
      - petstore_auth:
        - read:pets
      summary: Finds Pets by status
      tags:
      - pet
      x-accepts:
      - application/json
      - application/xml
  /pet/findByTags:
    get:
      deprecated: true
      description: Multiple tags can be provided with comma-separated strings.
      operationId: findPetsByTags
      parameters:
      - description: Tags to filter by
        explode: false
        in: query
        name: tags
        required: true
        schema:
          items:
            type: string
          type: array
          default: null
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Pet"
                type: array
                default: null
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/Pet"
                type: array
                default: null
          description: Successful operation
        "400":
          description: Invalid tag value
      security:
      - petstore_auth:
        - read:pets
      summary: Finds Pets by tags
      tags:
      - pet
      x-accepts:
      - application/json
      - application/xml
  /pet/{petId}:
    delete:
      description: Delete a pet by ID.
      operationId: deletePet
      parameters:
      - description: API key
        explode: false
        in: header
        name: api_key
        required: false
        schema:
          type: string
        style: simple
      - description: Pet ID to delete
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "400":
          description: Invalid pet value
      security:
      - api_key: []
      summary: Deletes a pet
      tags:
      - pet
      x-accepts:
      - application/json
    get:
      description: Returns a single pet.
      operationId: getPetById
      parameters:
      - description: ID of pet to return
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
            application/xml:
              schema:
                $ref: "#/components/schemas/Pet"
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
      security:
      - petstore_auth:
        - read:pets
      summary: Find pet by ID
      tags:
      - pet
      x-accepts:
      - application/json
      - application/xml
    post:
      description: Updates a pet's name and status using form parameters.
      operationId: updatePetWithForm
      parameters:
      - description: ID of pet that needs to be updated
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - description: Updated name of the pet
        explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      - description: Updated status of the pet
        explode: true
        in: query
        name: status
        required: false
        schema:
          type: string
        style: form
      responses:
        "405":
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
      summary: Updates a pet in the store with form data
      tags:
      - pet
      x-accepts:
      - application/json
  /store/inventory:
    get:
      description: Returns a map of status codes to quantities.
      operationId: getInventory
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  format: int32
                  type: integer
                type: object
          description: Successful operation
      security:
      - api_key: []
      summary: Returns pet inventories by status
      tags:
      - store
      x-accepts:
      - application/json
  /store/order:
    post:
      description: Place a new order in the store.
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
          application/xml:
            schema:
              $ref: "#/components/schemas/Order"
        description: Order object that needs to be added to the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
            application/xml:
              schema:
                $ref: "#/components/schemas/Order"
          description: Successful operation
        "400":
          description: Invalid Order
      security:
      - petstore_auth:
        - write:pets
      summary: Place an order for a pet
      tags:
      - store
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/xml
  /store/order/{orderId}:
    delete:
      description: For valid response try integer IDs with value <= 5 or > 10. Other
        values will generate exceptions.
      operationId: deleteOrder
      parameters:
      - description: ID of the order that needs to be deleted
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          maximum: 10
          minimum: 1
          type: integer
        style: simple
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Order not found
      security:
      - api_key: []
      summary: Delete purchase order by ID
      tags:
      - store
      x-accepts:
      - application/json
    get:
      description: For valid response try integer IDs with value <= 5 or > 10. Other
        values will generate exceptions.
      operationId: getOrderById
      parameters:
      - description: ID of order that needs to be fetched
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          maximum: 10
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
            application/xml:
              schema:
                $ref: "#/components/schemas/Order"
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Order not found
      security:
      - api_key: []
      summary: Find purchase order by ID
      tags:
      - store
      x-accepts:
      - application/json
      - application/xml
  /user:
    post:
      description: This can only be done by the logged-in user.
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
          application/xml:
            schema:
              $ref: "#/components/schemas/User"
        description: Created user object
        required: true
      responses:
        default:
          description: Successful operation
      security:
      - petstore_auth:
        - write:pets
      summary: Create user
      tags:
      - user
      x-content-type: application/json
      x-accepts:
      - application/json
  /user/createWithList:
    post:
      description: Creates multiple users from a supplied array.
      operationId: createUsersWithListInput
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: "#/components/schemas/User"
              type: array
              default: null
          application/xml:
            schema:
              items:
                $ref: "#/components/schemas/User"
              type: array
              default: null
        description: List of user objects
        required: true
      responses:
        "200":
          description: Successful operation
      security:
      - petstore_auth:
        - write:pets
      summary: Creates list of users with given input array
      tags:
      - user
      x-content-type: application/json
      x-accepts:
      - application/json
  /user/login:
    get:
      description: Login using username and password.
      operationId: loginUser
      parameters:
      - description: The username for login
        explode: true
        in: query
        name: username
        required: true
        schema:
          type: string
        style: form
      - description: The password for login
        explode: true
        in: query
        name: password
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
          description: Successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              explode: false
              schema:
                format: int32
                type: integer
              style: simple
            X-Expires-After:
              description: date in UTC when token expires
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "400":
          description: Invalid username/password
      security: []
      summary: Logs user into the system
      tags:
      - user
      x-accepts:
      - application/json
      - application/xml
  /user/logout:
    get:
      description: Logs out the current logged-in user.
      operationId: logoutUser
      responses:
        default:
          description: Successful operation
      security:
      - petstore_auth:
        - read:pets
        - write:pets
      summary: Logs out current logged-in user
      tags:
      - user
      x-accepts:
      - application/json
  /user/{username}:
    delete:
      description: This can only be done by the logged-in user.
      operationId: deleteUser
      parameters:
      - description: The user that needs to be deleted
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
      security:
      - petstore_auth:
        - write:pets
      summary: Delete user
      tags:
      - user
      x-accepts:
      - application/json
    get:
      description: Returns a single user.
      operationId: getUserByName
      parameters:
      - description: The name that needs to be fetched
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
            application/xml:
              schema:
                $ref: "#/components/schemas/User"
          description: Successful operation
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
      security:
      - petstore_auth:
        - read:pets
      summary: Get user by user name
      tags:
      - user
      x-accepts:
      - application/json
      - application/xml
    put:
      description: This can only be done by the logged-in user.
      operationId: updateUser
      parameters:
      - description: Name that needs to be updated
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
          application/xml:
            schema:
              $ref: "#/components/schemas/User"
        description: Updated user object
        required: true
      responses:
        default:
          description: Successful operation
      security:
      - petstore_auth:
        - write:pets
      summary: Updated user
      tags:
      - user
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    ApiResponse:
      example:
        code: 0
        type: type
        message: message
      properties:
        code:
          format: int32
          type: integer
        type:
          type: string
        message:
          type: string
    Pet:
      example:
        id: 0
        category:
          id: 6
          name: name
        name: name
        photoUrls:
        - photoUrls
        - photoUrls
        tags:
        - id: 1
          name: name
        - id: 1
          name: name
        status: available
      properties:
        id:
          format: int64
          type: integer
        category:
          $ref: "#/components/schemas/Category"
        name:
          type: string
        photoUrls:
          items:
            type: string
          type: array
          default: null
        tags:
          items:
            $ref: "#/components/schemas/Tag"
          type: array
          default: null
        status:
          description: Pet status in the store
          enum:
          - available
          - pending
          - sold
          type: string
      required:
      - name
      - photoUrls
    Category:
      example:
        id: 6
        name: name
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
    Tag:
      example:
        id: 1
        name: name
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
    Order:
      example:
        id: 0
        petId: 6
        quantity: 1
        shipDate: 2000-01-23T04:56:07.000+00:00
        status: placed
        complete: true
      properties:
        id:
          format: int64
          type: integer
        petId:
          format: int64
          type: integer
        quantity:
          format: int32
          type: integer
        shipDate:
          format: date-time
          type: string
        status:
          description: Order Status
          enum:
          - placed
          - approved
          - delivered
          type: string
        complete:
          type: boolean
    User:
      example:
        id: 0
        username: username
        firstName: firstName
        lastName: lastName
        email: email
        password: password
        phone: phone
        userStatus: 6
      properties:
        id:
          format: int64
          type: integer
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          description: User Status
          format: int32
          type: integer
    uploadFile_request:
      properties:
        additionalMetadata:
          description: Additional data to pass to server
          type: string
        file:
          description: file to upload
          format: binary
          type: string
  securitySchemes:
    api_key:
      in: header
      name: api_key
      type: apiKey
    petstore_auth:
      flows:
        implicit:
          authorizationUrl: https://petstore.swagger.io/oauth/authorize
          scopes:
            read:pets: read your pets
            write:pets: modify pets in your account
      type: oauth2

